// The starting "brain" of 20Q. Every object has a value for every question:
// 1 = yes, 0.5 = sometimes, 0 = no. The engine nudges these values after each
// game, so the toy gets smarter the more it is played.

export const CATEGORIES = ['animal', 'vegetable', 'mineral', 'other'];

export const QUESTIONS = [
  ['alive', 'Is it alive?'],
  ['mammal', 'Is it a mammal?'],
  ['bird', 'Is it a bird?'],
  ['fish', 'Is it a fish?'],
  ['reptile', 'Is it a reptile or amphibian?'],
  ['insect', 'Is it an insect or a bug?'],
  ['water', 'Does it live in water?'],
  ['pet', 'Can it be kept as a pet?'],
  ['farm', 'Would you find it on a farm?'],
  ['zoo', 'Would you find it in a zoo?'],
  ['africa', 'Does it live in Africa?'],
  ['fur', 'Does it have fur or hair?'],
  ['fly', 'Can it fly?'],
  ['swim', 'Can it swim?'],
  ['legs', 'Does it have legs?'],
  ['legs4', 'Does it have four legs?'],
  ['tail', 'Does it have a tail?'],
  ['meat', 'Does it eat meat?'],
  ['dangerous', 'Is it dangerous?'],
  ['big', 'Is it bigger than a person?'],
  ['breadbox', 'Is it bigger than a loaf of bread?'],
  ['pocket', 'Can it fit in your pocket?'],
  ['heavy', 'Is it heavy?'],
  ['pattern', 'Does it have stripes or spots?'],
  ['edible', 'Can you eat it?'],
  ['sweet', 'Does it taste sweet?'],
  ['fruit', 'Is it a fruit?'],
  ['tree', 'Does it grow on a tree?'],
  ['underground', 'Does it grow underground?'],
  ['cooked', 'Is it usually cooked before eating?'],
  ['flower', 'Does it have flowers or petals?'],
  ['green', 'Is it green?'],
  ['red', 'Is it red?'],
  ['yellow', 'Is it yellow or orange?'],
  ['brown', 'Is it brown?'],
  ['white', 'Is it white?'],
  ['black', 'Is it black?'],
  ['round', 'Is it round?'],
  ['soft', 'Is it soft?'],
  ['shiny', 'Is it shiny?'],
  ['sharp', 'Is it sharp or pointy?'],
  ['fragile', 'Does it break easily?'],
  ['metal', 'Is it made of metal?'],
  ['wood', 'Is it made of wood?'],
  ['plastic', 'Is it made of plastic?'],
  ['glass', 'Is it made of glass?'],
  ['cloth', 'Is it made of cloth or fabric?'],
  ['paper', 'Is it made of paper?'],
  ['liquid', 'Is it a liquid?'],
  ['natural', 'Is it found in nature?'],
  ['electric', 'Does it use electricity?'],
  ['screen', 'Does it have a screen?'],
  ['light', 'Does it give off light?'],
  ['hot', 'Is it hot?'],
  ['wheels', 'Does it have wheels?'],
  ['ride', 'Can you ride in it or on it?'],
  ['sit', 'Can you sit on it?'],
  ['kitchen', 'Would you find it in a kitchen?'],
  ['house', 'Would you find it in a house?'],
  ['outdoors', 'Is it usually found outdoors?'],
  ['sky', 'Is it found in the sky?'],
  ['valuable', 'Is it valuable?'],
  ['tool', 'Is it a tool?'],
  ['wear', 'Can you wear it?'],
  ['sport', 'Is it used for sports or play?'],
  ['music', 'Does it make music?'],
  ['sound', 'Does it make a sound?'],
  ['write', 'Is it used for reading or writing?'],
  ['clean', 'Is it used for cleaning?'],
].map(([id, text]) => ({ id, text }));

// Traits are space-separated question ids. A plain id means "yes", a "~"
// prefix means "sometimes". Anything not listed is "no".
const RAW = {
  animal: {
    dog: 'alive mammal pet fur legs legs4 tail meat swim breadbox sound house ~farm ~dangerous ~brown ~black ~white ~outdoors ~pattern',
    cat: 'alive mammal pet fur legs legs4 tail meat breadbox sound house soft ~outdoors ~pattern ~black ~white ~brown ~farm',
    horse: 'alive mammal fur legs legs4 tail big breadbox farm sound outdoors heavy ride sit ~pet ~brown ~black ~white ~swim ~zoo',
    cow: 'alive mammal fur legs legs4 tail big breadbox farm sound outdoors heavy edible cooked pattern black white ~brown',
    pig: 'alive mammal legs legs4 tail breadbox farm sound outdoors heavy edible cooked ~pet ~fur',
    sheep: 'alive mammal fur legs legs4 tail breadbox farm sound outdoors white soft ~edible ~cooked ~heavy ~black',
    chicken: 'alive bird legs farm sound outdoors breadbox edible cooked ~fly ~white ~brown ~pet',
    duck: 'alive bird fly swim legs water farm sound outdoors breadbox ~edible ~cooked ~white ~brown ~green',
    lion: 'alive mammal fur legs legs4 tail meat dangerous zoo africa big breadbox sound outdoors heavy yellow ~brown',
    tiger: 'alive mammal fur legs legs4 tail meat dangerous zoo big breadbox sound outdoors heavy swim pattern yellow black',
    elephant: 'alive mammal legs legs4 tail zoo africa big breadbox sound outdoors heavy swim ~dangerous ~ride',
    giraffe: 'alive mammal fur legs legs4 tail zoo africa big breadbox outdoors heavy pattern yellow brown',
    zebra: 'alive mammal fur legs legs4 tail zoo africa big breadbox sound outdoors heavy pattern black white',
    monkey: 'alive mammal fur legs tail zoo breadbox sound outdoors brown ~africa ~pet ~meat ~legs4',
    bear: 'alive mammal fur legs legs4 meat dangerous zoo big breadbox sound outdoors heavy swim brown ~black ~white ~tail',
    rabbit: 'alive mammal pet fur legs legs4 tail soft outdoors ~breadbox ~white ~brown ~farm ~edible ~house',
    mouse: 'alive mammal fur legs legs4 tail pocket sound ~pet ~house ~outdoors ~white ~brown',
    kangaroo: 'alive mammal fur legs tail zoo breadbox outdoors brown ~big ~dangerous',
    whale: 'alive mammal water swim tail big breadbox heavy sound natural ~meat ~black',
    dolphin: 'alive mammal water swim tail big breadbox sound meat zoo',
    snake: 'alive reptile tail meat dangerous swim zoo outdoors ~pet ~pattern ~green ~breadbox ~africa',
    frog: 'alive reptile water swim legs legs4 pocket green sound outdoors meat ~pet ~edible',
    turtle: 'alive reptile water swim legs legs4 tail pet outdoors green ~breadbox ~zoo ~brown ~heavy',
    crocodile: 'alive reptile water swim legs legs4 tail meat dangerous zoo africa big breadbox green heavy',
    shark: 'alive fish water swim tail meat dangerous big breadbox heavy ~zoo',
    goldfish: 'alive fish water swim tail pet pocket house yellow',
    eagle: 'alive bird fly legs meat outdoors sky dangerous breadbox brown white ~zoo',
    owl: 'alive bird fly legs meat outdoors sky sound breadbox brown ~white ~zoo',
    penguin: 'alive bird swim legs zoo breadbox meat water black white ~sound',
    parrot: 'alive bird fly legs pet sound zoo green red ~yellow ~breadbox ~house',
    bee: 'alive insect fly legs pocket sound outdoors pattern yellow black dangerous ~farm',
    butterfly: 'alive insect fly legs pocket outdoors sky pattern ~yellow ~black',
    spider: 'alive insect legs pocket meat house outdoors black ~dangerous',
    ant: 'alive insect legs pocket outdoors ~house ~black ~red',
    person: 'alive mammal legs fur sound house breadbox ~meat ~outdoors ~write ~swim ~dangerous',
  },
  vegetable: {
    apple: '~alive edible sweet fruit tree red round kitchen natural farm ~green ~yellow ~pocket',
    banana: '~alive edible sweet fruit tree yellow kitchen natural soft',
    orange: '~alive edible sweet fruit tree yellow round kitchen natural ~pocket',
    strawberry: '~alive edible sweet fruit red pocket natural kitchen soft farm pattern',
    grape: '~alive edible sweet fruit pocket natural kitchen round green ~red',
    watermelon: '~alive edible sweet fruit green red breadbox heavy natural farm round pattern ~kitchen',
    lemon: '~alive edible fruit tree yellow pocket natural kitchen',
    pineapple: '~alive edible sweet fruit yellow breadbox natural kitchen ~sharp ~brown ~green',
    coconut: '~alive edible fruit tree brown round natural white ~breadbox ~sweet ~heavy',
    carrot: '~alive edible underground yellow kitchen natural farm ~cooked ~pocket',
    potato: '~alive edible underground cooked brown kitchen natural farm ~pocket',
    tomato: '~alive edible fruit red round kitchen natural farm soft ~cooked ~pocket',
    lettuce: '~alive edible green kitchen natural farm soft',
    broccoli: '~alive edible green cooked kitchen natural farm ~flower',
    onion: '~alive edible underground round kitchen natural farm cooked white ~brown ~red',
    corn: '~alive edible yellow cooked kitchen natural farm ~sweet ~green',
    pumpkin: '~alive edible yellow round breadbox heavy natural farm outdoors ~cooked',
    peanut: '~alive edible underground brown pocket kitchen natural farm',
    mushroom: '~alive edible cooked natural outdoors brown white pocket soft ~dangerous ~kitchen',
    rose: 'alive flower red natural outdoors sharp ~green ~white ~yellow ~house ~valuable',
    sunflower: 'alive flower yellow natural outdoors breadbox farm ~big ~edible',
    tree: 'alive natural outdoors big breadbox heavy green brown wood ~fruit ~flower',
    cactus: 'alive natural outdoors green sharp ~flower ~house ~breadbox',
    grass: 'alive natural outdoors green soft farm',
  },
  mineral: {
    rock: 'natural outdoors heavy ~pocket ~breadbox ~brown ~black ~white ~round',
    diamond: 'natural valuable shiny pocket sharp ~wear ~white',
    gold: 'natural metal valuable shiny yellow heavy ~wear ~pocket',
    coin: 'metal pocket round shiny house ~valuable ~yellow',
    key: 'metal pocket shiny tool house',
    knife: 'metal sharp kitchen tool shiny dangerous house ~pocket ~wood',
    spoon: 'metal kitchen shiny house ~pocket ~plastic ~wood',
    hammer: 'metal tool heavy house ~wood ~breadbox',
    scissors: 'metal sharp tool house ~pocket ~plastic ~dangerous',
    nail: 'metal sharp pocket shiny house ~tool',
    sword: 'metal sharp dangerous heavy shiny breadbox ~valuable',
    ring: 'metal wear pocket shiny round valuable ~yellow',
    car: 'metal wheels ride sit outdoors big breadbox heavy sound glass valuable ~electric ~dangerous ~red ~black ~white',
    bicycle: 'metal wheels ride sit outdoors breadbox sport ~heavy',
    airplane: 'metal ride sit fly sky big breadbox heavy sound wheels electric glass valuable',
    train: 'metal wheels ride sit big breadbox heavy sound outdoors glass ~electric',
    phone: 'electric screen pocket sound house plastic glass valuable light fragile ~metal ~black',
    computer: 'electric screen house plastic metal valuable breadbox light ~heavy ~write ~sound',
    television: 'electric screen house sound plastic breadbox heavy light black ~valuable ~glass',
    mirror: 'glass shiny fragile house ~breadbox ~heavy',
    lamp: 'electric light house breadbox ~hot ~glass ~metal',
    bottle: 'glass fragile kitchen house ~breadbox ~plastic',
    salt: 'natural edible white kitchen house ~pocket',
    sand: 'natural outdoors yellow ~brown ~soft',
    water: 'liquid natural kitchen house outdoors ~edible ~sky',
  },
  other: {
    book: 'paper write house ~breadbox ~pocket',
    pencil: 'wood write pocket house yellow ~sharp ~tool',
    paper: 'paper write house white pocket ~fragile',
    money: 'paper valuable pocket green house',
    chair: 'sit house legs legs4 breadbox ~wood ~plastic ~metal ~soft',
    table: 'house legs legs4 wood breadbox heavy kitchen ~metal ~plastic',
    bed: 'house sit soft big breadbox heavy legs cloth ~legs4 ~wood ~white',
    door: 'house wood breadbox heavy ~big ~metal ~glass',
    house: 'big breadbox heavy outdoors sit ~wood ~glass ~electric',
    shirt: 'cloth wear soft house ~white',
    shoe: 'wear house ~breadbox ~cloth ~black ~brown ~sport ~outdoors',
    hat: 'wear cloth soft house ~outdoors ~black',
    sock: 'cloth wear soft pocket house ~white',
    pillow: 'soft cloth house white ~breadbox',
    'teddy bear': 'soft cloth house fur legs sport brown ~legs4 ~breadbox',
    ball: 'round sport outdoors ~plastic ~soft ~breadbox ~white ~red',
    guitar: 'wood music sound breadbox house ~electric ~shiny',
    umbrella: 'cloth outdoors breadbox ~metal ~black ~plastic',
    toothbrush: 'plastic clean house ~pocket',
    broom: 'clean house tool breadbox ~wood ~plastic',
    candle: 'hot light house ~white ~red ~pocket ~fragile',
    sun: 'natural hot light sky big breadbox round yellow heavy outdoors',
    moon: 'natural sky big breadbox round white heavy outdoors ~light',
    cloud: 'natural sky white soft big breadbox outdoors ~black',
    fire: 'natural hot light dangerous red yellow sound ~outdoors ~house',
  },
};

function parseTraits(traits) {
  const v = {};
  for (const token of traits.split(/\s+/).filter(Boolean)) {
    if (token.startsWith('~')) v[token.slice(1)] = 0.5;
    else v[token] = 1;
  }
  return v;
}

export const BASE_OBJECTS = Object.entries(RAW).flatMap(([category, items]) =>
  Object.entries(items).map(([name, traits]) => ({
    name,
    category,
    v: parseTraits(traits),
    fallback: 0,
  })),
);
